plugins {
    id "com.android.application"
}

android {
    namespace "com.nealaringale.nextbell"
    compileSdk 35

    defaultConfig {
        applicationId "com.nealaringale.nextbell"
        minSdk 26
        targetSdk 35
        def ciRun = System.getenv("GITHUB_RUN_NUMBER")
        versionCode = ciRun == null ? 4 : 1000 + ciRun.toInteger()
        versionName "0.4.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
